labels:
  - name: bug
    checkbox: "- [x] bug"
  - name: enhancement
    checkbox: "- [x] enhancement"
  - name: documentation
    checkbox: "- [x] documentation"
  - name: question
    checkbox: "- [x] question"
  - name: wontfix
    checkbox: "- [x] wontfix"