name: 'Checkbox Labeler'
description: 'Add labels to a PR based on checkboxes in the description.'
author: 'sarhatabaot'

branding:
  icon: 'tag'
  color: 'green'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  pr-number:
    description: 'The number of the pull request'
    required: true
  pr-body:
    description: 'The body of the pull request'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'